DROP TABLE IF EXISTS PubBook;
CREATE TABLE PubBook(
	ISBN	VARCHAR(10) NOT NULL,
    PubID	VARCHAR(10) NOT NULL,
    PubDate	VARCHAR(8),
    Payment	DECIMAL(18, 0),
    PRIMARY KEY(ISBN, PubID),
	FOREIGN KEY (ISBN) REFERENCES Books(ISBN),
	FOREIGN KEY (PubID) REFERENCES Publishers(PubID)
);
